//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Complete.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingProduct
    {
        public int BillingProductId { get; set; }
        public int ProductId { get; set; }
        public int BillingId { get; set; }
        public int Quantity { get; set; }
        public string Discount { get; set; }
    
        public virtual Billing Billing { get; set; }
        public virtual Product Product { get; set; }
    }
}
