//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Complete.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Billing()
        {
            this.BillingProducts = new HashSet<BillingProduct>();
        }
    
        public int BillingId { get; set; }
        public string TotalPrice { get; set; }
        public string TotalDiscount { get; set; }
        public string Amount { get; set; }
        public int CreatedBy { get; set; }
        public string Name { get; set; }
        public string Addres { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModfied { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingProduct> BillingProducts { get; set; }
    }
}
