//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Complete.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Quantity
    {
        public int QuantityId { get; set; }
        [DisplayName("Quantity")]
        public int Quantity1 { get; set; }
        public string Rate { get; set; }
        public int ProductId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModfied { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
